name: Release on crates.io
on:
  push:
    branches-ignore: '**'
    tags: v**

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: login
        args: ${{ secrets.CRATES_IO_TOKEN }}
    - uses: actions-rs/cargo@v1
      with:
        command: publish

